services:
  postgres:
    image: postgres:17
    container_name: physec_learn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - physec_learn_postgres_data:/var/lib/postgresql/data

volumes:
  physec_learn_postgres_data: